# Generated by Django 6.0.7 on 2026-08-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Undefined', max_length=50, verbose_name='Name')),
                ('major', models.CharField(default='Undefined', max_length=50, verbose_name='Major')),
                ('date', models.DateField(verbose_name='Date of obtaining')),
                ('location', models.CharField(default='Undefined', max_length=50, verbose_name='Location')),
            ],
        ),
    ]
