# Generated by Django 6.0.7 on 2026-08-29 19:17

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.upload_to_static, verbose_name='Certificate Image'),
        ),
    ]
