# Generated by Django 6.0.7 on 2026-08-29 19:37

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_certificate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=main.models.upload_pdf_to_static, verbose_name='Certificate PDF'),
        ),
    ]
