# Generated by Django 6.0.7 on 2026-08-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_certificate_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Undefined', max_length=80, verbose_name='Company Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_present', models.BooleanField(default=False, verbose_name='Is present?')),
                ('description', models.TextField(default='Undefined', max_length=800, verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(default='Undefined', max_length=50, verbose_name='College Name'),
        ),
    ]
