# Generated by Django 6.0.7 on 2026-08-29 21:55

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_experience_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.upload_to_static, verbose_name='Certificate Image')),
                ('github_repo', models.URLField(blank=True, null=True, verbose_name='Github Repo')),
                ('github_live', models.URLField(blank=True, null=True, verbose_name='Github Live')),
                ('project_title', models.CharField(default='Undefined', max_length=50, verbose_name='Project Title')),
                ('short_description', models.CharField(default='Undefined', max_length=50, verbose_name='Short Description')),
                ('long_description', models.TextField(blank=True, null=True, verbose_name='Long Description')),
            ],
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Technology')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_stack', to='main.project')),
            ],
        ),
    ]
