# Generated by Django 6.0.7 on 2026-08-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project_techstack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(default='Undefined', max_length=100, verbose_name='Short Description'),
        ),
    ]
