# Generated by Django 6.0.7 on 2026-08-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_certificate_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='colleges/', verbose_name='Project Image')),
                ('college_name', models.CharField(default='Undefined', max_length=50, verbose_name='College Name')),
                ('major', models.CharField(default='Undefined', max_length=50, verbose_name='Major')),
                ('degree', models.CharField(default='Undefined', max_length=30, verbose_name='Degree')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_present', models.BooleanField(default=False, verbose_name='Is present?')),
                ('location', models.CharField(default='Undefined', max_length=50, verbose_name='Location')),
            ],
        ),
    ]
