# Generated by Django 6.0.7 on 2026-08-30 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='is_present',
            new_name='is_current',
        ),
    ]
