# Generated by Django 6.0.7 on 2026-08-30 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_is_present_education_is_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='is_current',
            new_name='is_present',
        ),
    ]
