# Generated by Django 6.0.7 on 2026-08-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_is_current_education_is_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
